---
# run with ansible-playbook -v -i host.linux  oqengine/oq_work.yaml --limit 
#
- hosts: all
  order: sorted
  gather_facts: yes
  #
  become: yes
  vars:
    shared_nfs: /exports/shared
    inst_nfs: /opt/openquake
    nfs_mount_opts: "ro,proto=tcp,soft,intr,noauto"
    nfs_serv_opts: "(rw,fsid=0,crossmnt,insecure,no_subtree_check,async)"
    server_host: "{{hostvars['server']['ansible_default_ipv4']['address']}}"

  tasks:
  ##### Check OS for update system
  - name: ping hosts
    ping:

  - name: check OS and get variable
    debug: msg={{ansible_distribution}}-{{ansible_distribution_version}}-{{ansible_host}}-{{inventory_hostname}}-{{group_names}}
  
  - name: check IP
    debug: msg={{ ansible_default_ipv4.network }}-{{ansible_default_ipv4.netmask}}-{{ansible_default_ipv4.address}}

#### Setup NFS server on master and worker
#
  - name: Ensure NFS utilities are installed on Ubuntu master
    apt:
      name: "{{ item }}"
      state: latest
    loop:  [nfs-kernel-server, netbase]
    when: "'master' in group_names and ansible_distribution == 'Ubuntu' "
  
  - name: Enable NFS server service on Ubuntu master
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: started
      masked: no
    with_items:
       - nfs-kernel-server
    when: "'master' in group_names and ansible_distribution == 'Ubuntu' "

  - name: Ensure NFS utilities are installed on Ubuntu worker
    apt:
      name: "{{ item }}"
      state: latest
    loop:  [nfs-common, netbase]
    when: "'worker' in group_names and ansible_distribution == 'Ubuntu' "

### Centos
  - name: Ensure NFS utilities are installed on Centos
    yum:
      name: nfs-utils
      update_cache: yes
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Enable NFS server service on Centos  Master
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
       - rpcbind
       - nfs-server
    when: "'master' in group_names and ansible_distribution == 'CentOS' "

# Create Shared for NFS
#
  - name: Check "{{ shared_nfs }}"  folder exists
    stat:
     path: "{{ shared_nfs }}"
    register: workdir
 
  - name: "echo if directory already existed"
    debug:
      msg: "Shared  {{ shared_nfs }}  folder  is already existed"
    when: workdir.stat.exists
 
  - name: "Ansible Create directory {{ shared_nfs }} if not exists"
    file:
      path: "{{ shared_nfs }}"
      state: directory
      mode: "2770"
      group: openquake
      owner: openquake
    when: workdir.stat.exists == false 


  - name: "Add export line for NFS server for shared folder"
    lineinfile:
      path: /etc/exports
      line: "{{ shared_nfs }}     {{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}{{ nfs_serv_opts }}"
    when: "'master' in group_names"

  - name: "Add export line for NFS server for installation folder"
    lineinfile:
      path: /etc/exports
      line: "{{ inst_nfs }}     {{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}{{ nfs_serv_opts }}"
    notify: reload nfs   
    when: "'master' in group_names"

  - name: Set Mountpoints "{{ shared_nfs }}" for Openquake on Worker Cluster
    mount:
      path: "{{ shared_nfs }}"
      src: "{{ server_host }}:{{ shared_nfs }}"
      fstype: nfs4
      opts: "{{ nfs_mount_opts }}"
      state: mounted
    when: "'worker' in group_names"

  - name: Set Mountpoints "{{ shared_nfs }}" for Openquake on Worker Cluster
    mount:
      path: "{{ inst_nfs }}"
      src: "{{ server_host }}:{{ shared_nfs }}"
      fstype: nfs4
      opts: "{{ nfs_mount_opts }}"
      state: mounted
    when: "'worker' in group_names"

  handlers:
    - name: reload nfs
      command: 'exportfs -ra'
