---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: master
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:latest"
    command: /sbin/init 
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    groups:
      - master
  - name: worker1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1604}-ansible:latest"
    command: /sbin/init 
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    groups:
      - worker
  - name: worker2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: /sbin/init 
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    groups:
      - worker
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      ansible_verbosity: 1
  inventory:
    host_vars:
      etc_dir: /etc/openquake
      venv_dir: /opt/openquake
      venv_bin: "{{ venv_dir }}/bin"
      shared_nfs: /mnt/shared
      workdir_services: /var/lib/openquake
      webuidir_services: /var/lib/openquake/webui
      nfs_mount_opts: "ro,rsize=1048576,wsize=1048576,bg,soft,intr,noauto,tcp"
      nfs_serv_opts: "(ro,fsid=0,no_root_squash,nohide,insecure,no_subtree_check,async)"
      worker_nodes_zmq: "{{ groups['worker'] | map('extract', hostvars, ['ansible_ssh_host']) | join(' -1,') }} -1"
      worker_nodes_dask: "{{ groups['worker'] | map('extract', hostvars, ['ansible_ssh_host']) | join(' -1,') }} -1"
  lint:
    ansible-lint
scenario:
  cluster:
    - cleanup 
    - destroy
    - create
    - converge
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible

