
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: openquake
  name: openquake-webui
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths: 
      - backend:
          service: 
            name: engine-service
            port: 
              number: 8800
        path: /
        pathType: Prefix
