apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: oqjob
spec:
  minAvailable: 3
  schedulerName: volcano
  plugins:
    ssh: ["--ssh-key-file-path=/home/openquake/.ssh"]
    svc: []
    env: []
  tasks:
    - replicas: 1
      name: oqmaster
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          hostIPC: true
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  echo "sleep 10";
                  sleep 10;
                  sudo sed -i "s@^host = .*@host = $(cat /etc/volcano/oqmaster.host )@g;s/,/, /g" /opt/openquake/openquake.cfg;
                  sudo sed -i "s@^host_cores =.*@host_cores = $(cat /etc/volcano/oqworker.host | tr '\n' , | sed 's/,$//g' | sed 's/\(\.oqjob\)/\1 -1/g')@g;s/,/, /g" /opt/openquake/openquake.cfg;
                  echo "sleep 10";
                  sleep 10;
                  #start db server
                  /home/openquake/oq-db_start.sh;
                  sleep 3000;
                  oq engine --run "https://downloads.openquake.org/pkgs/test_event_based_risk_inputs_bc.zip"
              image: openquake/engine:exp
              name: master
              imagePullPolicy: Always
              #resources:
              #  limits:
              #    memory: "8Gi"
              #    cpu: "8"
              #  requests:
              #    memory: "4Gi"
              #    cpu: "4"
              ports:
                - containerPort: 8800
                  name: oqjob-port
              workingDir: /home/openquake
              volumeMounts:
              - name: shareddata
                mountPath: /oqdata
                readOnly: false
          volumes:
          - name: shareddata
            #emptyDir: {}
            hostPath:
              path: /k8s/data
          restartPolicy: Never
    - replicas: 2
      name: oqworker
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  sudo mkdir -p /var/run/sshd; sudo /usr/sbin/sshd -D;
              image: openquake/engine:exp
              imagePullPolicy: Always
              name: worker
              #resources:
              #  limits:
              #    memory: "8Gi"
              #    cpu: "8"
              #  requests:
              #    memory: "4Gi"
              #    cpu: "4"
              ports:
              ports:
                - containerPort: 8800
                  name: oqjob-port
              workingDir: /home/openquake
              volumeMounts:
              - name: shareddata
                mountPath: /oqdata
                readOnly: true
          volumes:
          - name: shareddata
            #emptyDir: {}
            hostPath:
              path: /k8s/data
          restartPolicy: OnFailure
---
