version: "3.7"

networks:
  frontend:
  backend:
    internal: true

volumes:
  oqdata:
  # oqdata-nfs:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: nfsvers=4,addr=nfs-server,rw
  #     device: ":/oqdata"

#definizione di un yaml template da usare poi negli altri servizi
x-op-service-default: &service_default
  restart: unless-stopped
  init: true

services:
  master:
    <<: *service_default
    container_name: engine-master
    hostname: engine-master
    image: openquake/engine-master-zmq:latest
    ports:
     - 8800:8800
    # Uncomment to enable auth in WebUI/API
    # environment:
    #   - LOCKDOWN=true
    volumes:
     - oqdata:/home/openquake/oqdata
    # Uncomment to expose demos inside the container
    # - ../../demos:/home/openquake/demos:ro
    # use different openquake.cfg from the docker image
     - ./openquake.cfg:/etc/openquake/openquake.cfg
    networks:
     backend:
      aliases:
       - engine-master
     frontend:
     #labels:

  worker:
    <<: *service_default
    # don't use name if want to scale
    # container_name: engine-worker
    hostname: engine-worker
    image: openquake/engine-worker-zmq:latest
    volumes:
     - oqdata:/home/openquake/oqdata:ro
    networks:
     backend:
      aliases:
       - engine-worker
    depends_on:
      - master
