apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataengine
  labels:
    usage: dataengine
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: dataengine
    readOnly: false
