name: macos_pyapp
'on':
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - actions

jobs:

  python3-8_devel_bigsur:
    name: BigSur Install develop mode on Python 3.8 using current branch
    runs-on: macos-11.0
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Set up Python 3.8 as default version on MacOS
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pytest to use with oqengine
        run: pip install pytest
      - name: Install requirements files
        run: pip install -r ./requirements-py38-macos.txt 
      - name: Run Installation of oq-engine in devel mode with osgeo
        run: pip install -e .[osgeo]
      - name: Run pytest to check GDAL
        run: pytest -vsx openquake/commands/tests/commands_test.py -k nrml


  python3-8_user_bigsur:
    name: BigSur Install User mode on Python 3.8 on master
    runs-on: macos-11.0
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Installation scripts in user mode
        run: python3.8 install.py user
