---
name: docker
on:
  workflow_dispatch:
    inputs:
      version:
        description: Image Tag 
        default: nightly
        required: true
  schedule:
    - cron: "0 23 * * *"
  push: 
    branches:
      - docker_build

jobs:
  docker:
    name: Build image and push after successfull calculation
    runs-on: ubuntu-latest

    steps:
  # This Checkout is necessary when using a context in docker/build-push-action
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image engine with tag nightly
        id: docker_engine
        run: docker build --build-arg oq_branch=master -t openquake/engine:nightly -f docker/Dockerfile.dev docker
      - name: List Image
        run: |
          docker image ls
      - name: Run calcs on single docker
        run: |
          time docker run openquake/engine:nightly "oq engine --run /usr/src/oq-engine/demos/risk/ScenarioDamage/job_hazard.ini /usr/src/oq-engine/demos/risk/ScenarioDamage/job_risk.ini"
      - name: push image engine with tag nightly on docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          DOCKER_TAG: ${{ github.event.inputs.version }}
        run: |
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          docker push openquake/engine:$DOCKER_TAG
