name: macos_pyapp
'on':
  push:
    branches:
      - macos
  schedule:
    - cron: "0 1 * * *"

jobs:

  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macos-latest, windows-latest, ubuntu-latest]
        os: [macos-10.15, macos-11.0]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          ref: macos
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Install pytest to use with oqengine
        run: pip3 install pytest
      - name: Install requirements files
        run: |
          echo "py"${{ matrix.python-version }} | tr -d . >> pyver
          env
          #pip3 install -r ./requirements-${{ pyver }}-macos.txt 
      - name: Run Installation of oq-engine in devel mode with osgeo
        run: pip3 install -e .[osgeo]
      - name: Run tests
        run: |
            oq dbserver start &
            pytest openquake
      - name: Run demos
        run: |
            oq reset -y
            oq dbserver start &
            ./bin/run-demos.sh demos
