name: macos_pyapp
'on':
  push:
    branches:
      - macos
  schedule:
    - cron: "0 1 * * *"

jobs:

  python_devel_catalina:
    name: Catalina Install develop mode on Python 3.7 
    runs-on: macos-10.15
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: check python3 version
        run: python3 --version
      - name: Install pytest to use with oqengine
        run: pip3 install pytest
      - name: Install requirements files
        run: pip3 install -r ./requirements-py37-macos.txt 
      - name: Run Installation of oq-engine in devel mode with osgeo
        run: pip3 install -e .[osgeo]
      - name: Run tests
        run: |
            oq dbserver start &
            pytest openquake
      - name: Run demos
        run: |
            oq reset -y
            oq dbserver start &
            ./bin/run-demos.sh demos

  python3-8_devel_bigsur:
    name: BigSur Install develop mode on Python 3.8 
    runs-on: macos-11.0
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: check python3 version
        run: python3 --version
      - name: Install pytest to use with oqengine
        run: pip3 install pytest
      - name: Install requirements files
        run: pip3 install -r ./requirements-py38-macos.txt 
      - name: Run Installation of oq-engine in devel mode with osgeo
        run: pip3 install -e .[osgeo]
      - name: Run tests
        run: |
            oq dbserver start &
            pytest openquake
      - name: Run demos
        run: |
            oq reset -y
            oq dbserver start &
            ./bin/run-demos.sh demos
