---
name: Installation Script for Windows

on:
  push:
    branches: [ windows ]
  schedule:
    - cron: "30 22 * * *"

jobs:
  install:
    runs-on: windows-latest
    env:
      GITHUB_PULL_REQUEST: ${{ github.event.number }}
      GITHUB_DEF_BR:  ${{ github.event.repository.default_branch }}
      GITHUB_REF:  ${{ github.ref }}
      GITHUB_HD_REF:  ${{ github.head_ref }}
      GITHUB_BS_REF:  ${{ github.base_ref }}
        #more $GITHUB_EVENT_PATH
    strategy:
      matrix:
        #python-version: [3.6, 3.8]
        python-version: [3.6]

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          ref: windows
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
    # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip and install requirements
        run: |
          git status
          pip install -U pip
    # Use script to install engine and not the pip install .
      - name: Install engine with install script
        run: |
          git status
          type install_win.py
          python3 install_win.py devel
      - name: Run demos to test installation
        run: oq engine --run "https://downloads.openquake.org/pkgs/test_event_based_risk_inputs_bc.zip"
